### ISSUE TITLE
Suggestions regarding the Documentation

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2257]
Here a list of suggestions regarding the Brython documentation :

- [ ] [[Syntax](https://brython.info/static_doc/en/syntax.html)] State that usage of `console.log()` should be preferred to `print()` for better output formatting, e.g. when printing HTMLElement ([more info](https://github.com/brython-dev/brython/issues/2255)).

**[This list is under construction]**

@PierreQuentel For each items, if you answer 'no', I'll remove them from the list.

**Comment by denis-migdal** [comment]
Here an example for the page menu :

![Screenshot 2023-10-05 at 19-39-46 KeyApp](https://github.com/brython-dev/brython/assets/16555663/9edbe6f6-5f8d-42b5-b083-546b388cbb3c)

```css
details {
	position:fixed;
	right:5em;
	top: 5em;
	z-index: 100;
	background: var(--color-box-body);
	border: 1px solid gray;
	border-radius: 5px;
	padding: 10px;
	padding-right:20px;
	margin-bottom: 0px;
	& > ul { margin-bottom:0px
	} }
```

````html
<details open=""><summary>Table of Contents</summary><ul>
<li>
<a href="#user-content-keyapp" rel="nofollow">KeyApp</a></li>
<ul>
<li>
<a href="#user-content-links" rel="nofollow">Links</a></li>
<li>
<a href="#user-content-commands" rel="nofollow">Commands</a></li>
<li>
<a href="#user-content-install" rel="nofollow">Install</a></li>
<li>
<a href="#user-content-custom-css" rel="nofollow">Custom CSS</a></li>
</ul>
</ul>
</details>
```
